export const tools = [
  { id: "move", label: "Move", key: "V" },
  { id: "brush", label: "Brush", key: "B" },
  { id: "eraser", label: "Eraser", key: "E" },
  { id: "rectangle", label: "Rectangle", key: "U" },
  { id: "ellipse", label: "Ellipse", key: "O" },
  { id: "text", label: "Text", key: "T" },
  { id: "hand", label: "Hand", key: "H" },
  { id: "eyedropper", label: "Sample color", key: "I" },
  { id: "crop", label: "Crop", key: "C" },
  { id: "marquee", label: "Marquee", key: "M" },
  { id: "lasso", label: "Lasso", key: "L" },
] as const;

export const blendModes = [
  "source-over",
  "multiply",
  "screen",
  "overlay",
  "darken",
  "lighten",
  "soft-light",
  "hard-light",
  "difference",
  "exclusion",
  "color-dodge",
  "color-burn",
  "hue",
  "saturation",
  "color",
  "luminosity",
] as const;
export const blendLabels: Record<(typeof blendModes)[number], string> = {
  "source-over": "Normal",
  multiply: "Multiply",
  screen: "Screen",
  overlay: "Overlay",
  darken: "Darken",
  lighten: "Lighten",
  "soft-light": "Soft light",
  "hard-light": "Hard light",
  difference: "Difference",
  exclusion: "Exclusion",
  "color-dodge": "Color dodge",
  "color-burn": "Color burn",
  hue: "Hue",
  saturation: "Saturation",
  color: "Color",
  luminosity: "Luminosity",
};
