/* auto-generated by NAPI-RS */
/* eslint-disable */

export declare class NativeEditor {
  constructor(options: string);
  snapshot(): string;
  dispatch(command: string): string;
  preview(): Promise<string>;
  save(path: string): Promise<string>;
  exportImage(path: string, jpeg: boolean): Promise<void>;
  importImages(paths: Array<string>): Promise<string>;
  sampleColor(x: number, y: number): Promise<string | null>;
  resizeCanvas(options: string): Promise<string>;
  close(): void;
}

export declare function openEditor(path: string): Promise<NativeEditor>;
