// Generated by cargo run -p picsie-core --bin export_types. Do not edit.
export type Point = { x: number; y: number };
export type Shape = "rectangle" | "ellipse";
export type FontFamily = "sans-serif" | "serif" | "monospace";
export type Blend =
  | "source-over"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "soft-light"
  | "hard-light"
  | "difference"
  | "exclusion"
  | "color-dodge"
  | "color-burn"
  | "hue"
  | "saturation"
  | "color"
  | "luminosity";
export type Sampling = "Nearest" | "Smooth" | "High";
export type Content =
  | { kind: "paint" }
  | { kind: "group" }
  | { kind: "shape"; shape: Shape; color: string }
  | { kind: "gradient"; from: string; to: string }
  | { kind: "text"; text: string; fontSize: number; fontFamily: FontFamily; color: string }
  | { kind: "image" };
export type MaskMode = "hide" | "reveal";
export type LayerMask = {
  enabled: boolean;
  base: MaskMode;
  linked: boolean;
  placement?: MaskPlacement;
};
export type MaskPlacement = {
  x: number;
  y: number;
  scaleX: number;
  scaleY: number;
  rotation: number;
  flipX: boolean;
  flipY: boolean;
};
export type Layer = {
  id: string;
  parentId?: string;
  name: string;
  visible: boolean;
  locked: boolean;
  width: number;
  height: number;
  x: number;
  y: number;
  scaleX: number;
  scaleY: number;
  rotation: number;
  flipX: boolean;
  flipY: boolean;
  opacity: number;
  blend: Blend;
  sampling: Sampling;
  brightness: number;
  saturation: number;
  blur: number;
  content: Content;
  mask?: LayerMask;
};
export type Document = {
  format: string;
  version: number;
  name: string;
  width: number;
  height: number;
  layers: Array<Layer>;
};
export type Viewport = { width: number; height: number; zoom: number; pan: Point };
export type Selection = { ids: Array<string>; anchor?: string };
export type HistoryInfo = {
  dirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  undoLabel: string;
  redoLabel: string;
  undoCount: number;
  revision: string;
};
export type Tool =
  | "move"
  | "brush"
  | "eraser"
  | "rectangle"
  | "ellipse"
  | "text"
  | "hand"
  | "eyedropper"
  | "crop"
  | "marquee"
  | "lasso";
export type PaintTarget = "content" | "mask";
export type SelectionMode = "replace" | "toggle" | "range";
export type Phase = "down" | "move" | "up" | "cancel";
export type Modifiers = { shift: boolean; alt: boolean };
export type PointerSample = { phase: Phase; point: Point; modifiers: Modifiers };
export type InitialDocument =
  | { kind: "demo" }
  | { kind: "new"; name: string; width: number; height: number };
export type Side = "above" | "below";
export type CanvasSizeOptions = { width: number; height: number; anchor: number; fill?: string };
export type CropRect = { x: number; y: number; width: number; height: number };
export type CropRatio = "free" | "original" | "square" | "fourThree" | "sixteenNine";
export type LayerRow = { id: string; depth: number; visible: boolean; collapsed: boolean };
export type SelectionBounds = { x: number; y: number; width: number; height: number };
export type MarqueeKind = "rectangle" | "ellipse";
export type PixelSelectionMode = "replace" | "add" | "subtract";
export type Command =
  | { type: "select"; id?: string; mode: SelectionMode }
  | { type: "selectAll" }
  | { type: "setTool"; tool: Tool }
  | { type: "fit" }
  | { type: "zoom"; zoom: number; point?: Point }
  | { type: "resizeViewport"; width: number; height: number }
  | { type: "pan"; delta: Point }
  | { type: "setViewport"; viewport: Viewport }
  | { type: "setColor"; color: string }
  | { type: "setBrush"; size: number; opacity: number }
  | { type: "updateLayer"; patch: Partial<Layer> }
  | { type: "addPaintLayer" }
  | { type: "addGradient" }
  | { type: "addGroup" }
  | { type: "groupSelected" }
  | { type: "toggleGroupExpansion"; id: string }
  | { type: "moveToGroup"; parentId?: string }
  | { type: "duplicate" }
  | { type: "remove" }
  | { type: "reorder"; direction: number }
  | { type: "reorderTo"; targetId: string; side: Side }
  | { type: "nudge"; delta: Point }
  | { type: "resizeCanvas"; options: CanvasSizeOptions }
  | { type: "setCropRatio"; ratio: CropRatio }
  | { type: "commitCrop" }
  | { type: "cancelCrop" }
  | { type: "setMarqueeKind"; kind: MarqueeKind }
  | { type: "setSelectionMode"; mode: PixelSelectionMode }
  | { type: "deselectPixels" }
  | { type: "selectAllPixels" }
  | { type: "clearSelectedPixels" }
  | { type: "addMask"; base: MaskMode }
  | { type: "setPaintTarget"; target: PaintTarget }
  | { type: "setMaskMode"; mode: MaskMode }
  | { type: "resetMask"; base: MaskMode }
  | { type: "removeMask" }
  | { type: "toggleMaskLink" }
  | { type: "undo" }
  | { type: "redo" }
  | { type: "finishGesture" }
  | { type: "cancelGesture" }
  | { type: "pointer"; samples: Array<PointerSample> };
export type EditorState = {
  document: Document;
  history: HistoryInfo;
  selection: Selection;
  paintTarget: PaintTarget;
  maskMode: MaskMode;
  tool: Tool;
  color: string;
  brushSize: number;
  brushOpacity: number;
  viewport: Viewport;
  cropRect: CropRect | null;
  cropRatio: CropRatio;
  layerRows: Array<LayerRow>;
  pixelSelectionBounds: SelectionBounds | null;
  marqueeKind: MarqueeKind;
  selectionMode: PixelSelectionMode;
};
