// Generated by cargo run -p picsie-core --bin export_types. Do not edit.
export type Point = { x: number; y: number };
export type CursorHint =
  | "arrow"
  | "text"
  | "crosshair"
  | "move"
  | "copy"
  | "hand"
  | "rotate"
  | "resizeHorizontal"
  | "resizeDiagonalDown"
  | "resizeVertical"
  | "resizeDiagonalUp";
export type HandleGeometry = { centers: Array<Point>; zoom: number; rotation: boolean };
export type CursorMap = {
  crop: CropRect | null;
  crop_active: boolean;
  crop_movable: boolean;
  brush_diameter: number | null;
  origin: Point;
  viewport_zoom: number;
  default: CursorHint;
  handles: HandleGeometry | null;
  guides: Array<CanvasGuide>;
  zoom: number;
  movable: boolean;
  pickable: Array<Array<Point>>;
};
export type GuideAxis = "horizontal" | "vertical";
export type CanvasGuide = { id: string; axis: GuideAxis; position: number };
export type ViewOptions = {
  rulers: boolean;
  guides: boolean;
  grid: boolean;
  lockGuides: boolean;
  snap: boolean;
  snapGuides: boolean;
  snapGrid: boolean;
  snapLayers: boolean;
  snapBounds: boolean;
  autoSelect: boolean;
  showControls: boolean;
};
export type TextAlignment = "left" | "center" | "right";
export type TextNavigation = "up" | "down" | "lineStart" | "lineEnd";
export type TextLayout = {
  fontName: string;
  alignment: TextAlignment;
  tracking: number;
  leading: number;
  point: boolean;
};
export type TextPatch = {
  text?: string;
  fontSize?: number;
  fontName?: string;
  alignment?: TextAlignment;
  tracking?: number;
  leading?: number;
  color?: string;
};
export type TextSelection = { anchor: number; head: number };
export type SnapLines = { xs: Array<number>; ys: Array<number> };
export type Shape = "rectangle" | "ellipse";
export type FontFamily = "sans-serif" | "serif" | "monospace";
export type Blend =
  | "source-over"
  | "multiply"
  | "screen"
  | "overlay"
  | "darken"
  | "lighten"
  | "soft-light"
  | "hard-light"
  | "difference"
  | "exclusion"
  | "color-dodge"
  | "color-burn"
  | "hue"
  | "saturation"
  | "color"
  | "luminosity"
  | "linear-burn"
  | "linear-dodge"
  | "vivid-light"
  | "linear-light"
  | "pin-light"
  | "hard-mix"
  | "subtract"
  | "divide";
export type Sampling = "Nearest" | "Smooth" | "High";
export type Content =
  | { kind: "paint" }
  | { kind: "group" }
  | { kind: "shape"; shape: Shape; color: string }
  | { kind: "gradient"; from: string; to: string }
  | { kind: "text"; text: string; fontSize: number; fontFamily: FontFamily; color: string }
  | { kind: "image" };
export type MaskMode = "hide" | "reveal";
export type LayerMask = {
  enabled: boolean;
  base: MaskMode;
  linked: boolean;
  placement?: MaskPlacement;
};
export type MaskPlacement = {
  sampling: Sampling;
  x: number;
  y: number;
  scaleX: number;
  scaleY: number;
  rotation: number;
  flipX: boolean;
  flipY: boolean;
};
export type Layer = {
  id: string;
  parentId?: string;
  maskSourceId?: string;
  name: string;
  visible: boolean;
  locked: boolean;
  width: number;
  height: number;
  x: number;
  y: number;
  scaleX: number;
  scaleY: number;
  rotation: number;
  flipX: boolean;
  flipY: boolean;
  opacity: number;
  blend: Blend;
  sampling: Sampling;
  brightness: number;
  saturation: number;
  blur: number;
  adjustment?: LayerAdjustment;
  content: Content;
  textLayout?: TextLayout;
  mask?: LayerMask;
};
export type Document = {
  format: string;
  version: number;
  resolution: number;
  name: string;
  width: number;
  height: number;
  layers: Array<Layer>;
  guides: Array<CanvasGuide>;
};
export type Viewport = { width: number; height: number; zoom: number; pan: Point };
export type Selection = { ids: Array<string>; anchor?: string };
export type HistoryInfo = {
  dirty: boolean;
  canUndo: boolean;
  canRedo: boolean;
  undoLabel: string;
  redoLabel: string;
  undoCount: number;
  revision: string;
};
export type Tool =
  | "move"
  | "brush"
  | "eraser"
  | "rectangle"
  | "ellipse"
  | "text"
  | "hand"
  | "eyedropper"
  | "crop"
  | "marquee"
  | "lasso"
  | "wand";
export type TransformField = "x" | "y" | "width" | "height" | "rotation" | "scalePercent";
export type LassoKind = "freehand" | "polygonal";
export type WandSettings = {
  tolerance: number;
  /**
   * Point / 3×3 / 5×5 average: radius 0 / 1 / 2.
   */
  radius: number;
  contiguous: boolean;
  sampleAllLayers: boolean;
};
export type ImageSizeOptions = {
  width: number;
  height: number;
  resolution: number;
  sampling: Sampling;
};
export type PaintTarget = "content" | "mask";
export type SelectionMode = "replace" | "toggle" | "range";
export type Phase = "down" | "move" | "up" | "cancel";
export type Modifiers = { shift: boolean; alt: boolean; control: boolean; meta: boolean };
export type PointerSample = { phase: Phase; point: Point; modifiers: Modifiers };
export type InitialDocument =
  | { kind: "demo" }
  | { kind: "new"; name: string; width: number; height: number };
export type Side = "above" | "below";
export type CanvasSizeOptions = { width: number; height: number; anchor: number; fill?: string };
export type CropRect = { x: number; y: number; width: number; height: number };
export type CropRatio = "free" | "original" | "square" | "fourThree" | "sixteenNine";
export type LayerRow = {
  id: string;
  depth: number;
  visible: boolean;
  collapsed: boolean;
  canToggleClipping: boolean;
};
export type SelectionBounds = { x: number; y: number; width: number; height: number };
export type MarqueeKind = "rectangle" | "ellipse";
export type PixelSelectionMode = "replace" | "add" | "subtract";
export type AdjustmentKind = "Levels" | "Curves";
export type LevelsChannel = "RGB" | "Red" | "Green" | "Blue";
export type LevelRange = {
  black: number;
  gamma: number;
  white: number;
  outputBlack: number;
  outputWhite: number;
};
export type LevelsSettings = {
  channel: LevelsChannel;
  ranges: [LevelRange, LevelRange, LevelRange, LevelRange];
};
export type LevelsSample = "black" | "gray" | "white";
export type LevelsAuto = "contrast" | "color" | "neutral";
export type CurvePoint = { x: number; y: number };
export type CurvesSettings = {
  channel: LevelsChannel;
  channels: [Array<CurvePoint>, Array<CurvePoint>, Array<CurvePoint>, Array<CurvePoint>];
};
export type LayerAdjustment = {
  kind: AdjustmentKind;
  hue: number;
  saturation: number;
  lightness: number;
  colorize: boolean;
  levels: LevelsSettings;
  curves: CurvesSettings;
};
export type Command =
  | { type: "setSelectionAntialiased"; antialiased: boolean }
  | { type: "setTransformRatio"; locked: boolean }
  | { type: "setTransformField"; field: TransformField; value: number }
  | { type: "selectLayerPixels" }
  | { type: "beginDistort" }
  | { type: "distortLayer"; corners: [Point, Point, Point, Point] }
  | { type: "setDisplayScale"; scale: number }
  | { type: "setTextCaretVisible"; visible: boolean }
  | { type: "typeOpacityDigit"; digit: number }
  | { type: "stepBrushHardness"; increase: boolean }
  | { type: "selectTextUnit"; point: Point; paragraph: boolean }
  | { type: "updateText"; patch: TextPatch }
  | { type: "commitText" }
  | { type: "cancelText" }
  | { type: "setTextSelection"; anchor: number; head: number }
  | { type: "moveTextCaret"; direction: TextNavigation; extend: boolean }
  | { type: "setViewOptions"; options: ViewOptions }
  | { type: "beginGuide"; axis: GuideAxis; point: Point }
  | { type: "finishGuide"; delete: boolean }
  | { type: "addGuide"; axis: GuideAxis; position: number }
  | { type: "clearGuides" }
  | { type: "select"; id?: string; mode: SelectionMode }
  | { type: "selectAll" }
  | { type: "setTool"; tool: Tool }
  | { type: "fit" }
  | { type: "zoom"; zoom: number; point?: Point }
  | { type: "resizeViewport"; width: number; height: number }
  | { type: "pan"; delta: Point }
  | { type: "setViewport"; viewport: Viewport }
  | { type: "setPaletteColor"; color: string; background: boolean }
  | { type: "setSampledForeground"; color: string }
  | { type: "swapPaletteColors" }
  | { type: "resetPaletteColors" }
  | { type: "setTextColor"; color: string; draft_id: string | null }
  | { type: "previewBlendMode"; id: string | null; mode: Blend | null }
  | { type: "cycleBlendMode"; forward: boolean }
  | { type: "beginVisibilitySwipe"; id: string }
  | { type: "swipeVisibility"; id: string }
  | { type: "endVisibilitySwipe" }
  | { type: "copyMask"; source_id: string; target_id: string }
  | { type: "loadThumbnailSelection"; id: string; mask: boolean; mode: PixelSelectionMode }
  | { type: "duplicateTo"; target_id: string; side: Side; into: boolean }
  | { type: "setMaskPlacement"; placement: MaskPlacement }
  | { type: "distortMask"; corners: [Point, Point, Point, Point] }
  | { type: "setColor"; color: string }
  | { type: "setBrush"; size: number; opacity: number }
  | { type: "setBrushTip"; hardness: number; smoothing: number }
  | { type: "updateLayer"; patch: Partial<Layer> }
  | { type: "addPaintLayer" }
  | { type: "addGradient" }
  | { type: "addGroup" }
  | { type: "groupSelected" }
  | { type: "toggleGroupExpansion"; id: string }
  | { type: "moveToGroup"; parentId?: string }
  | { type: "duplicate" }
  | { type: "layerViaCopy" }
  | { type: "mergeLayers" }
  | { type: "addAdjustment"; kind: AdjustmentKind }
  | { type: "beginAdjustmentEdit"; id: string }
  | { type: "updateAdjustmentLevels"; settings: LevelsSettings; preview: boolean }
  | { type: "updateAdjustmentCurves"; settings: CurvesSettings; preview: boolean }
  | { type: "setAdjustmentPreview"; preview: boolean }
  | { type: "autoLevels"; mode: LevelsAuto }
  | { type: "sampleLevels"; point: Point; mode: LevelsSample }
  | { type: "setLevelsSampleMode"; mode: LevelsSample | null }
  | { type: "cancelAdjustmentEdit" }
  | { type: "commitAdjustmentEdit" }
  | { type: "beginTransform" }
  | { type: "commitTransform" }
  | { type: "cancelTransform" }
  | { type: "moveSelection"; delta: Point }
  | { type: "movePixels"; delta: Point; duplicate: boolean }
  | { type: "setLassoKind"; kind: LassoKind }
  | { type: "finishSelection" }
  | { type: "removeSelectionPoint" }
  | { type: "setWand"; settings: WandSettings }
  | { type: "resizeImage"; options: ImageSizeOptions }
  | { type: "remove" }
  | { type: "reorder"; direction: number }
  | { type: "reorderTo"; targetId: string; side: Side }
  | { type: "nudge"; delta: Point }
  | { type: "resizeCanvas"; options: CanvasSizeOptions }
  | { type: "setCropRatio"; ratio: CropRatio }
  | { type: "commitCrop" }
  | { type: "cancelCrop" }
  | { type: "setMarqueeKind"; kind: MarqueeKind }
  | { type: "setSelectionMode"; mode: PixelSelectionMode }
  | { type: "deselectPixels" }
  | { type: "cancelPixelSelection" }
  | { type: "selectAllPixels" }
  | { type: "clearSelectedPixels" }
  | { type: "fillSelection" }
  | { type: "fillBackground" }
  | { type: "invertSelection" }
  | { type: "expandSelection"; amount: number }
  | { type: "contractSelection"; amount: number }
  | { type: "featherSelection"; amount: number }
  | { type: "editText"; id?: string; point?: Point }
  | { type: "beginPropertyEdit"; label: string }
  | { type: "pickUnder"; point: Point }
  | { type: "addMask"; base: MaskMode }
  | { type: "setPaintTarget"; target: PaintTarget }
  | { type: "setMaskMode"; mode: MaskMode }
  | { type: "resetMask"; base: MaskMode }
  | { type: "removeMask" }
  | { type: "toggleMaskLink" }
  | { type: "toggleMaskLinkFor"; id: string }
  | { type: "toggleClippingMask" }
  | { type: "toggleClippingFor"; id: string }
  | { type: "linkMask"; sourceId: string }
  | { type: "undo" }
  | { type: "redo" }
  | { type: "finishGesture" }
  | { type: "cancelGesture" }
  | { type: "pointer"; samples: Array<PointerSample> };
export type EditorState = {
  document: Document;
  history: HistoryInfo;
  selection: Selection;
  paintTarget: PaintTarget;
  maskMode: MaskMode;
  tool: Tool;
  color: string;
  backgroundColor: string;
  blendPreview: [string, Blend] | null;
  transformTarget: Layer | null;
  maskDistortion: [Point, Point, Point, Point] | null;
  imageDistortion: [Point, Point, Point, Point] | null;
  brushSize: number;
  brushOpacity: number;
  brushHardness: number;
  brushSmoothing: number;
  viewport: Viewport;
  cropRect: CropRect | null;
  cropRatio: CropRatio;
  layerRows: Array<LayerRow>;
  hasPixelSelection: boolean;
  canToggleClipping: boolean;
  canEditPixels: boolean;
  maskSourceIds: Array<string>;
  pixelSelectionBounds: SelectionBounds | null;
  pixelSelectionFeather: number | null;
  marqueeKind: MarqueeKind;
  selectionMode: PixelSelectionMode;
  textEditRequests: bigint;
  lassoKind: LassoKind;
  wand: WandSettings;
  selectionDraft: boolean;
  transformActive: boolean;
  selectionAntialiased: boolean;
  canModifySelection: boolean;
  selectionEmpty: boolean;
  locksTransformRatio: boolean;
  transformScalePercent: number;
  selectionDraftMode: PixelSelectionMode | null;
  canCopyPixels: boolean;
  viewOptions: ViewOptions;
  displayedGuides: Array<CanvasGuide>;
  guideDragActive: boolean;
  snapLines: SnapLines;
  textEditing: boolean;
  textCaretVisible: boolean;
  cursorMap: CursorMap;
  textSelection: TextSelection;
  currentText: Layer;
  textCaret: Point | null;
};
