[package]
name = "picsie-core"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = "1"
serde = { version = "1", features = ["derive", "rc"] }
serde_json = "1"
uuid = { version = "1", features = ["v4", "serde"] }
base64 = "0.22"
skia-safe = { version = "0.153.3", features = ["textlayout"] }
ts-rs = { version = "12", features = ["serde-json-impl"] }
tempfile = "3"
png = "0.17"

tiff = { version = "0.11.3", default-features = false }
