[package]
name = "electropic-native"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
crate-type = ["cdylib"]

[dependencies]
electropic-core = { path = "../electropic-core" }
napi = { version = "3", features = ["napi8", "async", "serde-json"] }
napi-derive = "3"
serde_json = "1"

[build-dependencies]
napi-build = "2"

